Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -5,22 +5,36 @@ on:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
+    
+env:
+  CI_PROJECT_DIR: $GITHUB_WORKSPACE
 
 jobs:
   build:
 
     runs-on: ubuntu-latest
-
+    
+    defaults:
+      run:
+        working-directory: ./app
+        
     steps:
     - uses: actions/checkout@v3
     - name: pip install gcovr
       run: pip install gcovr
-    - name: make_gcov
-      run: cd fast_test/tutorial/c;make test GCOV=1
-    - name: make coco
-      run: export CI_PROJECT_DIR=`pwd`;cd fast_test/tutorial/c;make coco
-    - uses: 5monkeys/cobertura-action@master
+    - name: Make with GCOV and Test
+      run: make test GCOV=1
+    - name: Generate Code Coverage
+      run: make coco
+    - name: Publish Cobertura Report
+      uses: 5monkeys/cobertura-action@master
       with:
-          path: fast_test/tutorial/c/coverage.xml.xml
-          minimum_coverage: 10
+          path: fast_test/tutorial/c/coverage.xml
+          minimum_coverage: 10  
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'xml_data/test_results*.xml'
+
 
